AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev

Resources:
 
  AppStarShips:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/StarShips/serverless.yml
      Parameters:
        Environment: dev    

Outputs:
  
  AppStarShips:
    Description: App Informe StarShips
    Value: !Ref AppStarShips
  

