AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev

Resources:
  #Funcion Lambda para Token
  AppInspRiesgoAccessTokenJWT:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoAccessTokenJWT/serverless.yml
      Parameters:
        Environment: dev
        TablaInspeccion: Inspeccion
        TablaTokenDetail: tw-token-detail
        TablaUserDetail: user-detail

  #Funcion Lambda para InspRiesgoRegistroSolicitud
  AppInspRiesgoRegistroSolicitud:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoRegistroSolicitud/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction
        TablaInspeccion: Inspeccion
        TablaDatosTramite: Inspeccion
        TablaGrupoRamos: Ramos
        TablaContactoCliente: ContactoCliente
        TablaValoresDeclarados: ValoresDeclarados        

  #Funcion Lambda para InspRiesgoRegistroSolicitud
  AppInspRiesgoEnvioArchivos:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoEnvioArchivos/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction
   
  #Funcion Lambda para Georeferenciacion
  AppInspRiesgoGeoReferenciacion:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoGeoReferenciacion/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction

  #Funcion Lambda para Informe General
  AppInspRiesgoInformeGeneral:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoInformeGeneral/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction

  #Funcion Lambda para check list empresarial 
  AppInspCheckListEmpresarial:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspCheckListEmpresarial/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction
        
  #Funcion Lambda para check list empresarial   
  AppInspRiesgoListaSolicitud:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoListaSolicitud/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction

  AppInspRiesgoParametroComun:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoParametroComun/serverless.yml  
      Parameters:
        Environment: dev
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction
  
  AppInspRiesgoNotificacion:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoNotificacion/serverless.yml  
      Parameters:
        Environment: dev

  AppInspRiesgoEnvioInforme:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoEnvioInforme/serverless.yml  
      Parameters:
        Environment: dev
        TablaInspeccion: Inspeccion
        TablaArchivo: Archivo
        CodInformeGenerado: "03"
        CodInformeInspeccionado: "04"
        Hostname: "api.pre.mapfre.com.pe"
        IndDel: "0"
        Path: "/app/commonServices/api/v1.0/login"
        RiesgoEnvioArchivo: "InspRiesgoEnvioArchivos-dev"
        TipArchivo: "8"
        CredencialesEnvioInforme: "CredencialesEnvioInforme"
        # LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction

  AppInspRiesgoGeneraClaveDinamica:
      Type: AWS::Serverless::Application
      Properties:
        Location: Functions/InspRiesgoGeneraClaveDinamica/serverless.yml  
        Parameters:
          Environment: dev
          TablaClaveTemp: clave-dim-temp
          TablaClaveTempHist: clave-dim-temp-hist

  AppInspRiesgoInformeConstruccion:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoInformeConstruccion/serverless.yml
      #templateDetail.yml
      Parameters:
        Environment: dev
        LambdaInspRiesgoNotificacion: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoNotificacion
        LambdaInspRiesgoInformeGeneral: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoInformeGeneral
        LambdaInspRiesgoEnvioInforme: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoEnvioInforme
        LambdaInspRiesgoGeoReferenciacion: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoGeoReferenciacion
        LambdaInspRiesgoListaSolicitud: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoListaSolicitud
        LambdaInspRiesgoParametroComun: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoParametroComun
        LambdaInspCheckListEmpresarial: arn:aws:lambda:us-east-1:486520098236:function:InspCheckListEmpresarial
        LambdaInspRiesgoGeneraClaveDinamica: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoGeneraClaveDinamica
        LambdaInspRiesgoEnvioArchivos: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoEnvioArchivos
        LambdaInspRiesgoGeneraInforme: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoGeneraInforme
        LambdaNotificar: arn:aws:lambda:us-east-1:486520098236:function:Notificar  
        LambdaInspeccionSolicitud: arn:aws:lambda:us-east-1:486520098236:function:InspeccionSolicitud    
        TablaInspeccion: Inspeccion
        TablaDetalle: Riesgo
        TablaSiniestro: Siniestro
        TablaArchivo: Archivo
        TablaEnlace: Enlace
        BucketTemplate: archivos-solicitud
        KeyTemplate: Ejemplo.html\
        TablaDatosTramite: Inspeccion
        TablaGrupoRamos: Ramos
        TablaPerdida: Perdida
        TablaContactoCliente: ContactoCliente
        TablaValoresDeclarados: ValoresDeclarados
        TablaClaveTemp: clave-dim-temp
        TablaClaveTempHist: clave-dim-temp-hist
        LambdaToken: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWTFunction

  AppInspRiesgoGeneraInforme:
      Type: AWS::Serverless::Application
      Properties:
        Location: Functions/InspRiesgoGeneraInforme/serverless.yml  
        Parameters:
          Environment: dev

  AppNotificar:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/Notificar/serverless.yml
      Parameters:
        Environment: dev
        TablaNotificacion: Notificacion
        TablaInspeccion: Inspeccion
        Administrador: fmchoy@stefanini.com

  AppInspeccionSolicitud:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspeccionSolicitud/serverless.yml  
      Parameters:
        Environment: dev
        BucketTemplate: archivos-solicitud
        KeyTemplate: Ejemplo.html\
        TablaInspeccion: Inspeccion

  #API para el token TEMP
  # InspRiesgoAccessTokenJWT:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: Api/InspRiesgoAccessTokenJWT/template.yml
  #     Parameters:
  #       Environment: dev
  #       LambdaInspRiesgoAccessTokenJWTArn: !GetAtt AppInspRiesgoAccessTokenJWT.Outputs.InspRiesgoAccessTokenJWT
  #       ApiRole: !GetAtt AppInspRiesgoInformeConstruccion.Outputs.ApiRole

  #API para el Informe General
  # InspRiesgoInformeGeneral:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: Api/InspRiesgoInformeGeneral/template.yml
  #     Parameters:
  #       Environment: dev
  #       InspRiesgoInformeGeneralFunction: !GetAtt AppInspRiesgoInformeGeneral.Outputs.InspRiesgoInformeGeneralFunction
        #InspRiesgoInformeGeneralRole: !GetAtt AppInspRiesgoInformeGeneral.Outputs.InspRiesgoInformeGeneralRole

  
  
          # ApiRole: !GetAtt AppInspRiesgoGeneraClaveDinamica.Outputs.ApiRole

  #CREACION STEPFUNCTION LOGIN
  InspRiesgoLoginMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoLoginMachine/template.yml
      Parameters:
        Environment: dev
        # LambdaInspRiesgoGeneraClaveDinamica: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoGeneraClaveDinamica
        # LambdaInspRiesgoNotificacion: arn:aws:lambda:us-east-1:486520098236:function:InspRiesgoNotificacion
        LambdaInspRiesgoGeneraClaveDinamica: !GetAtt AppInspRiesgoGeneraClaveDinamica.Outputs.InspRiesgoGeneraClaveDinamicaFunction
        LambdaInspRiesgoNotificacion: !GetAtt AppInspRiesgoNotificacion.Outputs.InspRiesgoNotificacionFunction
  
  InspInformeMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoInformeMachine/template.yml
      Parameters:
        Environment: dev
        LambdaInspRiesgoGeneraInforme: !GetAtt AppInspRiesgoGeneraInforme.Outputs.InspRiesgoGeneraInformeFunction
        LambdaNotificar: !GetAtt AppNotificar.Outputs.NotificarFunction
        LambdaInspRiesgoEnvioInforme: !GetAtt AppInspRiesgoEnvioInforme.Outputs.InspRiesgoEnvioInformeFunction
  
  RegistroSolicitudMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: Functions/InspRiesgoSolicitudRegistroMachine/template.yml
      Parameters:
        Environment: dev
        LambdaInspRiesgoRegistroSolicitud: !GetAtt AppInspRiesgoRegistroSolicitud.Outputs.InspRiesgoRegistroSolicitudFunction
        LambdaNotificar: !GetAtt AppNotificar.Outputs.NotificarFunction
        LambdaInspeccionSolicitud: !GetAtt AppInspeccionSolicitud.Outputs.InspeccionSolicitudFunction

Outputs:
  
  AppInspRiesgoAccessTokenJWT:
    Description: App Riesgo Token
    Value: !Ref AppInspRiesgoAccessTokenJWT

  AppInspRiesgoRegistroSolicitud:
    Description: App Riesgo Token
    Value: !Ref AppInspRiesgoRegistroSolicitud

  AppInspRiesgoInformeConstruccion:
    Description: App Informe Construccion
    Value: !Ref AppInspRiesgoInformeConstruccion
  
  AppInspRiesgoParametroComun:
    Description: App ParametroComun
    Value: !Ref AppInspRiesgoParametroComun

  AppInspRiesgoListaSolicitud:
    Description: App ListaSolicitud
    Value: !Ref AppInspRiesgoListaSolicitud

  AppInspRiesgoInformeGeneral:
    Description: App Informe General
    Value: !Ref AppInspRiesgoInformeGeneral  

  AppInspCheckListEmpresarial:
    Description: App check list empresarial
    Value: !Ref AppInspCheckListEmpresarial

  AppInspRiesgoGeoReferenciacion:
    Description: App Georeferenciacion
    Value: !Ref AppInspRiesgoGeoReferenciacion
  
  AppInspRiesgoNotificacion:
    Description: App RiesgoNotificacion
    Value: !Ref AppInspRiesgoNotificacion

  AppInspRiesgoEnvioInforme:
    Description: App RiesgoEnvioInforme
    Value: !Ref AppInspRiesgoEnvioInforme

  AppInspRiesgoGeneraClaveDinamica:
    Description: App GeneraClaveDinamica
    Value: !Ref AppInspRiesgoGeneraClaveDinamica
    
  AppInspRiesgoEnvioArchivos:
    Description: App Georeferenciacion
    Value: !Ref AppInspRiesgoEnvioArchivos

  AppInspRiesgoGeneraInforme:
    Description: App InspRiesgoGeneraInforme
    Value: !Ref AppInspRiesgoGeneraInforme

  AppInspeccionSolicitud:
    Description: App InspeccionSolicitud
    Value: !Ref AppInspeccionSolicitud

