AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Plantilla para crear los recursos de la función de InspRiesgoParametroComun

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev
  LambdaToken:
    Type: String
    Description: ARN de la Lambda del token
    Default: "abc"

Resources:
  InspRiesgoParametroComunApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join
        - ""
        - - InspRiesgoParametroComunApi
          - "-"
          - !Ref Environment
      StageName: !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../../Api/InspRiesgoParametroComun/definitions.yml

  InspRiesgoParametroComunRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ""
        - - InspRiesgoParametroComunRole
          - !Ref Environment
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "apigateway.amazonaws.com"
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "Lambda"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
        - PolicyName: "DynamoCRUD"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: '*'
        - PolicyName: CWL
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetLogRecord
                  - logs:PutDestination
                  - logs:PutLogEvents
                  - logs:PutQueryDefinition
                  - logs:UpdateLogDelivery
                Resource: '*'   

  InspRiesgoParametroComunFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - ""
        - - InspRiesgoParametroComun
          - "-"
          - !Ref Environment
      Description: Funcion para obtener el token
      CodeUri: ../../Functions/InspRiesgoParametroComun/
      Handler: handler.excecute
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt InspRiesgoParametroComunRole.Arn
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          DATAPARAMETRO_TABLE: DataParametro
          PARAMETRO_TABLE: Parametro
          TOKEN_VALIDATE_API_HOST: 2v8b73crjf.execute-api.us-east-1.amazonaws.com
          TOKEN_VALIDATE_API_PATH: /default/InspRiesgoAccessTokenJWT/check-token

Outputs:
  InspRiesgoParametroComunApi:
    Description: Arn  de la API
    Value: !Ref InspRiesgoParametroComunApi
    
  InspRiesgoParametroComunRole:
    Description: Arn  de Role
    Value: !GetAtt InspRiesgoParametroComunRole.Arn

  InspRiesgoParametroComunFunction:
    Description: Arn de la Funcion InspRiesgoParametroComun
    Value: !GetAtt InspRiesgoParametroComunFunction.Arn


