AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Plantilla para crear los recursos del step functions

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev
  LambdaInspRiesgoGeneraInforme:
    Type: String
    Description: Funcion que genera la clave dinamica
  LambdaInspRiesgoEnvioInforme:
    Type: String
    Description: Funcion que genera la notificacion
  LambdaNotificar:
    Type: String
    Description: Funcion que genera la notificacion


Resources:
  InspRiesgoInformeMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../../Workflows/InspInformeMachine/definitions.json
      DefinitionSubstitutions:
        FUNCTION_GENERAR_INFORME: !Ref LambdaInspRiesgoGeneraInforme
        FUNCTION_ENVIO_INFORME: !Ref LambdaInspRiesgoEnvioInforme
        FUNCTION_NOTIFICAR: !Ref LambdaNotificar
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaInspRiesgoGeneraInforme
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaInspRiesgoEnvioInforme
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaNotificar