swagger: "2.0"
info:
  description: "Permite listar las solicitudes de Informe de Inspección de riesgo de inspector, se listan los datos desde DynamoDB AWS"
  version: "v1.0"
  title: "Servicio Cloud para listar las solicitudes de Informe de Inspección de riesgo de inspector, se listan los datos desde DynamoDB AWS"
  contact: 
    email: "soporte@mapfre.com.pe"    
  license: 
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0.html"    

schemes:
- "https"

x-amazon-apigateway-request-validators:
  body-validate:
    validateRequestBody: false
    validateRequestParameters: true

x-amazon-apigateway-gateway-responses:
  ACCESS_DENIED:
    statusCode: 403
    responseTemplates:
      application/json: " \n
          { \n
            \"exito\": false,
            \"mensaje\": \"Error en la operación\",
            \"data\": \"\",
            \"errores\": [
              {
                \"codigo\": \"1\",
                \"mensaje\": \"Error de validación de token, u acceso\"
              }
            ]
          }"

  UNAUTHORIZED:
    statusCode: 401
    responseTemplates:
      application/json: " \n
          { \n
            \"exito\": false,
            \"mensaje\": \"Error en el autorización\",
            \"data\": \"\",
            \"errores\":$context.error.messageString
          }"

securityDefinitions:
  autorizador:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri:
        Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaToken}/invocations"
      authorizerCredentials:
        Fn::GetAtt: "InspRiesgoListaSolicitudRole.Arn"
      authorizerResultTtlInSeconds: 300
      type: "token"
x-amazon-apigateway-request-validator: body-validate

paths:
  /:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"

  /InspListaSolicitud/{correo}/{clave}:
    options:
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "200 response"
            schema:
              $ref: "#/definitions/Empty"
            headers:
              Access-Control-Allow-Origin:
                type: "string"
              Access-Control-Allow-Methods:
                type: "string"
              Access-Control-Allow-Headers:
                type: "string"
        x-amazon-apigateway-integration:
          responses:
            default:
              statusCode: "200"
              responseParameters:
                method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
          passthroughBehavior: "when_no_match"
          requestTemplates:
            application/json: "{\"statusCode\": 200}"
          type: "mock"
    get:
      tags: 
        - inspeccion-riesgo-ListaSolicitud-cloud-service-handler      
      summary: "Permite listar Inspecciones"
      operationId: "listar"
      description: "Permite listar inspecciones \n"
      security:
        - autorizador: []   
      consumes:
        - "application/json"
      produces:
        - "application/json"
      x-amazon-apigateway-request-validator: body-validate
      parameters:
        - name: correo
          in: path
          description: "Información del correo del Inspector"
          required: true
          type: string
        - name: clave
          in: path
          description: "Numero del trámite"
          required: true
          type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: "InspRiesgoListaSolicitudRole.Arn"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InspRiesgoListaSolicitudFunction.Arn}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        requestTemplates:
          application/json: " \n
          #set($allParams = $input.params()) \n
          #set($inputRoot = $input.json('$')) \n
           {
             \"action\": \"listar\", \n
              \"params\" : { \n
                #foreach($type in $allParams.keySet()) \n
                #set($params = $allParams.get($type)) \n
                \"$type\" : { \n
                  #foreach($paramName in $params.keySet()) \n
                  \"$paramName\" : \"$util.escapeJavaScript($params.get($paramName))\" \n
                  #if($foreach.hasNext),#end \n
                  #end \n
                } \n
                #if($foreach.hasNext),#end \n
                #end \n
              }, \n
              \"data\": $inputRoot \n
            }"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
      responses:
        200:
          description: "Operación exitosa"
          schema:
            $ref: "#/definitions/ResponseSolicitud"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        401:
          description: "Error de authenticación"
        500:
          description: "Error en el servidor"
definitions:
  ResponseSolicitud:
    type: "object"
    title: "List Request Schema"
    required:
    - exito
    - mensaje
    properties:
      exito:
        type: boolean
      mensaje:
        type: string
      data:
        $ref: "#/definitions/ListSolicitud"
      errores:
        $ref: "#/definitions/ListError"

  ListSolicitud:
    type: array
    items:
      $ref: "#/definitions/Solicitud"

  ListError:
    type: array
    items:
      $ref: "#/definitions/Error"

  Error:
    type: "object"
    properties:
      exito:
        type: boolean
      mensaje:
        type: string
      data:
        type: string
      errores:
        type: string

  Empty:
    type: "object"

  Solicitud:
    type: "object"
    title: "Response Schema"
    required:
    - claveTramite
    - codEstadoTramite
    - nombreEstadoTramite
    - codTipoDocumento
    - tipoDocumento
    - numeroDocumento
    - nombreCliente
    - codInspector
    - fechaSolicitud
    - fechaActualizacion
    - fechaInspeccion
    - fechaVencimiento
    - dirección
    properties:
      claveTramite:
        type: string
      codEstadoTramite:
        type: string
      nombreEstadoTramite:
        type: string
      codTipoDocumento:
        type: string
      tipoDocumento:
        type: string
      numeroDocumento:
        type: string
      nombreCliente:
        type: string
      codInspector:
        type: string
      fechaSolicitud:
        type: string
      fechaActualizacion:
        type: string
      fechaInspeccion:
        type: string
      fechaVencimiento:
        type: string
      dirección:
        type: string