AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Plantilla para crear los recursos de la función StarShips

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev

Resources:

  StarShipsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join
        - ""
        - - StarShips
          - "-"
          - !Ref Environment
      StageName: !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../../Api/StarShips/definitions.yml

  StarShipsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ""
        - - StarShipsRole
          - !Ref Environment
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "apigateway.amazonaws.com"
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "Lambda"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"          
                Resource: "*"
        - PolicyName: DynamoCRUD
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource: '*'        
        - PolicyName: CWL
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetLogRecord
                  - logs:PutDestination
                  - logs:PutLogEvents
                  - logs:PutQueryDefinition
                  - logs:UpdateLogDelivery
                Resource: '*'   

  StarShipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - ""
        - - StarShips
          - "-"
          - !Ref Environment
      Description: Funcion para registrar ylistar  StarShips
      CodeUri: ../../Functions/StarShips/
      Handler: handler.procesar
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt StarShipsRole.Arn
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          ENVIRONMENT: !Ref Environment
          TABLE_STARSHIPS: STARSHIPS

Outputs:
  StarShipsRole:
    Description: Arn  de Role
    Value: !GetAtt StarShipsRole.Arn

  StarShipsFunction:
    Description: Arn de la Funcion
    Value: !GetAtt StarShipsFunction.Arn

  StarShipsApi:
    Description: Arn  de la API
    Value: !Ref StarShipsApi
 