AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Plantilla para crear los recursos del step functions

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev
  LambdaInspRiesgoRegistroSolicitud:
    Type: String
    Description: Funcion que genera la clave dinamica
  LambdaInspeccionSolicitud:
    Type: String
    Description: Funcion que genera la notificacion
  LambdaNotificar:
    Type: String
    Description: Funcion que genera la notificacion


Resources:

  RegistroSolicitudMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../../Workflows/RegistroSolicitudMachine/definitions.json
      DefinitionSubstitutions: 
        FUNCTION_DATA_SOLICITUD: !Ref LambdaInspRiesgoRegistroSolicitud
        FUNCTION_INSPECCION_SOLICITUD: !Ref LambdaInspeccionSolicitud
        FUNCTION_NOTIFICAR: !Ref LambdaNotificar

      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaInspRiesgoRegistroSolicitud
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaInspeccionSolicitud
        - LambdaInvokePolicy:
            FunctionName: !Ref LambdaNotificar