AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Plantilla para crear los recursos del step functions

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev
  LambdaInspRiesgoGeneraClaveDinamica:
    Type: String
    Description: Funcion que genera la clave dinamica
  LambdaInspRiesgoNotificacion:
    Type: String
    Description: Funcion que genera la notificacion

Resources:

  RoleInspeccionSolicitud:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ""
        - - InspeccionSolicitudRole
          - !Ref Environment
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: DynamoCRUD
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource: '*'        
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketPolicy"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                Resource: '*'
        - PolicyName: CWL
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetLogRecord
                  - logs:PutDestination
                  - logs:PutLogEvents
                  - logs:PutQueryDefinition
                  - logs:UpdateLogDelivery
                Resource: '*'    
        - PolicyName: Lambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'    


  RoleInspeccion:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ""
        - - InspeccionRole
          - !Ref Environment
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: DynamoCRUD
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource: '*'        
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketPolicy"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                Resource: '*'
        - PolicyName: CWL
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetLogRecord
                  - logs:PutDestination
                  - logs:PutLogEvents
                  - logs:PutQueryDefinition
                  - logs:UpdateLogDelivery
                Resource: '*'    

  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Funcion para hacer la query a dynamodb
      CodeUri: ../../Functions/InspRiesgoLoginMachine/
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt RoleInspeccion.Arn

  InspRiesgoLoginMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../../Workflows/InspRiesgoLoginMachine/definitions.json
      Role: !GetAtt  RoleInspeccionSolicitud.Arn
      DefinitionSubstitutions:
        FUNCTION_QUERY: !Ref QueryFunction
        FUNCTION_CLAVE_DINAMICA: !Ref LambdaInspRiesgoGeneraClaveDinamica
        FUNCTION_NOTIFICACION: !Ref LambdaInspRiesgoNotificacion
      #Policies:
      #  - LambdaInvokePolicy:
      #      FunctionName: !Ref LambdaInspRiesgoGeneraClaveDinamica
      #  - LambdaInvokePolicy:
      #      FunctionName: !Ref LambdaInspRiesgoNotificacion