swagger: "2.0"
info:
  description: "Realiza la lista de parámetro de solicitud de inspección en la base de datos"
  version: "v1.0"
  title: "Servicio Cloud para Realiza la lista de parámetro de solicitud de inspección en la base de datos"
  contact: 
    email: "soporte@mapfre.com.pe"    
  license: 
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0.html"    

schemes:
- "https"

x-amazon-apigateway-request-validators:
  body-validate:
    validateRequestBody: false
    validateRequestParameters: true

x-amazon-apigateway-gateway-responses:
  ACCESS_DENIED:
    statusCode: 403
    responseTemplates:
      application/json: " \n
          { \n
            \"exito\": false,
            \"mensaje\": \"Error en la operación\",
            \"data\": \"\",
            \"errores\": [
              {
                \"codigo\": \"1\",
                \"mensaje\": \"Error de validación de token, u acceso\"
              }
            ]
          }"

  UNAUTHORIZED:
    statusCode: 401
    responseTemplates:
      application/json: " \n
          { \n
            \"exito\": false,
            \"mensaje\": \"Error en el autorización\",
            \"data\": \"\",
            \"errores\":$context.error.messageString
          }"

securityDefinitions:
  autorizador:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri:
        Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaToken}/invocations"
      authorizerCredentials:
        Fn::GetAtt: "InspRiesgoParametroComunRole.Arn"
      authorizerResultTtlInSeconds: 300
      type: "token"
x-amazon-apigateway-request-validator: body-validate

paths:
  /:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"

  /InspRiesgoParametroComun/listar/{grupo}:
    options:
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "200 response"
            schema:
              $ref: "#/definitions/Empty"
            headers:
              Access-Control-Allow-Origin:
                type: "string"
              Access-Control-Allow-Methods:
                type: "string"
              Access-Control-Allow-Headers:
                type: "string"
        x-amazon-apigateway-integration:
          responses:
            default:
              statusCode: "200"
              responseParameters:
                method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
          passthroughBehavior: "when_no_match"
          requestTemplates:
            application/json: "{\"statusCode\": 200}"
          type: "mock"
    get:
      tags: 
        - Listar Parámetros
      summary: "Permite listar Parametros por grupo y tipo parametro"
      operationId: "listar"
      description: "Permite listar parametros \n"
      security:
        - autorizador: []   
      consumes:
        - "application/json"
      produces:
        - "application/json"
      x-amazon-apigateway-request-validator: body-validate
      parameters:
        - name: grupo
          in: path
          description: "Información del codigo de Grupo"
          required: true
          type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: "InspRiesgoParametroComunRole.Arn"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InspRiesgoParametroComunFunction.Arn}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        requestTemplates:
          application/json: " \n
          #set($allParams = $input.params()) \n
          #set($inputRoot = $input.json('$')) \n
           {
             \"action\": \"listar\", \n
              \"params\" : { \n
                #foreach($type in $allParams.keySet()) \n
                #set($params = $allParams.get($type)) \n
                \"$type\" : { \n
                  #foreach($paramName in $params.keySet()) \n
                  \"$paramName\" : \"$util.escapeJavaScript($params.get($paramName))\" \n
                  #if($foreach.hasNext),#end \n
                  #end \n
                } \n
                #if($foreach.hasNext),#end \n
                #end \n
              }, \n
              \"data\": $inputRoot \n
            }"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
      responses:
        200:
          description: "Operación exitosa"
          schema:
            $ref: "#/definitions/ResponseParametro"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        401:
          description: "Error de authenticación"
        500:
          description: "Error en el servidor"

  /InspRiesgoParametroComun/listar/{grupo}/{parametro}:
    options:
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "200 response"
            schema:
              $ref: "#/definitions/Empty"
            headers:
              Access-Control-Allow-Origin:
                type: "string"
              Access-Control-Allow-Methods:
                type: "string"
              Access-Control-Allow-Headers:
                type: "string"
        x-amazon-apigateway-integration:
          responses:
            default:
              statusCode: "200"
              responseParameters:
                method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
          passthroughBehavior: "when_no_match"
          requestTemplates:
            application/json: "{\"statusCode\": 200}"
          type: "mock"
    get:
      tags: 
        - Listar Parámetros
      summary: "Permite listar Parametros por grupo y tipo parametro"
      operationId: "listar"
      description: "Permite listar parametros \n"
      security:
        - autorizador: []   
      consumes:
        - "application/json"
      produces:
        - "application/json"
      x-amazon-apigateway-request-validator: body-validate
      parameters:
        - name: grupo
          in: path
          description: "Información del codigo de Grupo"
          required: true
          type: string
        - name: parametro
          in: path
          description: "Código Parámetro"
          required: true
          type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: "InspRiesgoParametroComunRole.Arn"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InspRiesgoParametroComunFunction.Arn}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        requestTemplates:
          application/json: " \n
          #set($allParams = $input.params()) \n
          #set($inputRoot = $input.json('$')) \n
           {
             \"action\": \"listar\", \n
              \"params\" : { \n
                #foreach($type in $allParams.keySet()) \n
                #set($params = $allParams.get($type)) \n
                \"$type\" : { \n
                  #foreach($paramName in $params.keySet()) \n
                  \"$paramName\" : \"$util.escapeJavaScript($params.get($paramName))\" \n
                  #if($foreach.hasNext),#end \n
                  #end \n
                } \n
                #if($foreach.hasNext),#end \n
                #end \n
              }, \n
              \"data\": $inputRoot \n
            }"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
      responses:
        200:
          description: "Operación exitosa"
          schema:
            $ref: "#/definitions/ResponseParametro"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        401:
          description: "Error de authenticación"
        500:
          description: "Error en el servidor"
  
  /InspRiesgoParametroComun/listar-todo:
    options:
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "200 response"
            schema:
              $ref: "#/definitions/Empty"
            headers:
              Access-Control-Allow-Origin:
                type: "string"
              Access-Control-Allow-Methods:
                type: "string"
              Access-Control-Allow-Headers:
                type: "string"
        x-amazon-apigateway-integration:
          responses:
            default:
              statusCode: "200"
              responseParameters:
                method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
          passthroughBehavior: "when_no_match"
          requestTemplates:
            application/json: "{\"statusCode\": 200}"
          type: "mock"
    get:
      tags: 
        - Listar Parámetros
      summary: "Permite listar todos los Parametros por grupo y tipo parametro"
      operationId: "listar"
      description: "Permite listar todos los parametros \n"
      security:
        - autorizador: []   
      consumes:
        - "application/json"
      produces:
        - "application/json"
      x-amazon-apigateway-request-validator: body-validate
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: "InspRiesgoParametroComunRole.Arn"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InspRiesgoParametroComunFunction.Arn}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        requestTemplates:
          application/json: " \n
          #set($allParams = $input.params()) \n
          #set($inputRoot = $input.json('$')) \n
           {
             \"action\": \"listar-todo\", \n
              \"params\" : { \n
                #foreach($type in $allParams.keySet()) \n
                #set($params = $allParams.get($type)) \n
                \"$type\" : { \n
                  #foreach($paramName in $params.keySet()) \n
                  \"$paramName\" : \"$util.escapeJavaScript($params.get($paramName))\" \n
                  #if($foreach.hasNext),#end \n
                  #end \n
                } \n
                #if($foreach.hasNext),#end \n
                #end \n
              }, \n
              \"data\": $inputRoot \n
            }"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
      responses:
        200:
          description: "Operación exitosa"
          schema:
            $ref: "#/definitions/ResponseParametro"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        401:
          description: "Error de authenticación"
        500:
          description: "Error en el servidor"

definitions:
  ResponseParametro:
    type: "object"
    title: "Response Parametro"
    required:
    - exito
    - mensaje
    properties:
      exito:
        type: boolean
      mensaje:
        type: string
      data:
        $ref: "#/definitions/ListParametro"
      errores:
        $ref: "#/definitions/ListError"

  ListParametro:
    type: array
    items:
      $ref: "#/definitions/Parametro"

  ListError:
    type: array
    items:
      $ref: "#/definitions/Error"
      
  Empty:
    type: "object"
    
  Parametro:
    type: "object"
    title: "Parametro"
    required:
    - codUsuregis
    - indRegactual
    - fecInidatcat
    - desDatacat
    - desCorta
    - codEstado
    - codDatacat
    - numTransaccion
    - desAcronimo
    - codUsumodif
    - fecInicat
    - fecFindatcat
    - fecFinvigorig
    - fecRegis
    - fecModif
    - codCatalogo
    properties:
      codUsuregis:
        type: string
      indRegactual:
          type: string
      fecInidatcat:
          type: string
      desDatacat:
          type: string
      desCorta:
          type: string
      codEstado:
          type: string
      codDatacat:
          type: string
      numTransaccion:
          type: string
      desAcronimo:
          type: string
      codUsumodif:
          type: string
      fecInicat:
          type: string
      fecFindatcat:
          type: string
      fecFinvigorig:
          type: string
      fecRegis:
          type: string
      fecModif:
          type: string
      codCatalogo:
          type: string
          
  Error:
    type: "object"
    properties:
      exito:
        type: boolean
      mensaje:
        type: string
      data:
        type: string
      errores:
        type: string
