AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Plantilla para crear los recursos del proyecto de Inspeccion de Riesgos

Parameters:
  Environment:
    Type: String
    Description: Valor del entorno
    Default: dev
  LambdaInspRiesgoNotificacion:
    Type: String
    Description: ARN de la funcion lambda InspRiesgoNotificacion
  TablaInspeccion:
    Type: String
    Description: Nombre de la tabla de inspeccion
  TablaMensajeMail:
    Type: String
    Description: Nombre de la tabla MensajeMail
  TablaCorreoElectronico:
    Type: String
    Description: Nombre de la tabla CorreoElectronico
  
Resources:

  ApiRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ApiRoleInspeccion-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "Lambda"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  InspeccionSolicitudRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - ""
        - - InspeccionSolicitudRole
          - !Ref Environment
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: DynamoCRUD
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource: '*'        
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketPolicy"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                Resource: '*'
        - PolicyName: CWL
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetLogRecord
                  - logs:PutDestination
                  - logs:PutLogEvents
                  - logs:PutQueryDefinition
                  - logs:UpdateLogDelivery
                Resource: '*'    

  InspRiesgoNotificacion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - ""
        - - InspRiesgoNotificacion
          - "-"
          - !Ref Environment
      Description: Permite generar y verificar el access token con JWT, guarda el acceso token en la base  DynamoDB datos Access token 
      CodeUri: Functions/InspRiesgoNotificacion/
      Handler: handler.enviar
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt RoleInspRiesgoNotificacion.Arn
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          ENVIRONMENT: !Ref Environment
          INSPECCIONES_TABLE: !Ref TablaInspeccion
          MENSAJEMAIL_TABLE: !Ref TablaMensajeMail
          CORREOELECTRONICO_TABLE: !Ref TablaCorreoElectronico
  
  ApiInspRiesgoNotificacion:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join 
        - "" 
        - - InspRiesgoNotificacion
          - "-"
          - !Ref Environment
      StageName: !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
           # Location: Api/InspRiesgoNotificacion/definitions.yml